import Link from "next/link";
import {
  ShortVersion,
  Roast,
  Receipt,
  PullStat,
  Ticket,
  Sources,
} from "../../components/blog/Widgets";
import ContrastChecker from "../../components/blog/ContrastChecker";

export default function Body() {
  return (
    <>
      <p>
        Vibe-coded apps ship a predictable set of UX defects: gray-on-white
        text, dead focus states, ARIA that lies, silent errors, and edge states
        nobody generated. Predictable is the good news. You built the app in a
        weekend; you can catch its worst UX problems in an afternoon, because
        they are the same problems every AI frontend has.
      </p>
      <p>
        This is not a lecture about vibe coding. Shipping fast is the correct
        move, and you are in large company:{" "}
        <a
          href="https://techcrunch.com/2025/03/06/a-quarter-of-startups-in-ycs-current-cohort-have-codebases-that-are-almost-entirely-ai-generated/"
          target="_blank"
          rel="noopener noreferrer"
        >
          for a quarter of YC&rsquo;s W25 batch, 95% of the code was
          AI-generated
        </a>
        . This is a field guide to vibe-coded app UX: what Lovable, Bolt, v0,
        and Cursor reliably get wrong, why they all get the <em>same</em>{" "}
        things wrong, and how to check your own app before your users do it
        for you.
      </p>

      <ShortVersion>
        <li>
          AI frontends fail in a repeating pattern: low contrast, missing focus
          states, broken ARIA, swallowed errors, absent empty states, sub-24px
          targets, and forms that re-ask known information.
        </li>
        <li>
          84% of ChatGPT-generated websites contained accessibility violations
          in a 2024 study of 88 developers&rsquo; prompts (W4A 2024).
        </li>
        <li>
          A Lovable-built site scored 100% on automated axe checks. A blind
          screen-reader user hit serious barriers within minutes (Axess Lab,
          May 2026). Passing automated checks is not the same as working.
        </li>
        <li>
          Humans are not better, only different: 95.9% of the top million home
          pages have detectable WCAG failures (WebAIM, 2026). AI just
          mass-produces the pattern.
        </li>
        <li>
          A 20-minute pass (keyboard-only walk, contrast check, screen-reader
          smoke test, error hunt) catches most of it. No tooling required.
        </li>
      </ShortVersion>

      <h2>Why AI frontends fail the same way every time</h2>
      <p>
        AI frontends fail identically because the models learned frontend from
        the public web, and the public web fails identically. The{" "}
        <a
          href="https://webaim.org/projects/million/"
          target="_blank"
          rel="noopener noreferrer"
        >
          WebAIM Million (2026 edition)
        </a>{" "}
        found detectable WCAG failures on 95.9% of the top million home pages,
        averaging 56.1 errors per page. Low-contrast text sits on 83.9% of
        them; 51% have unlabeled form inputs. Train on that, and low-contrast
        unlabeled output is not a bug in the model. It is the curriculum.
      </p>
      <p>
        The second cause is what the model optimizes for: looking right in a
        screenshot. A{" "}
        <a
          href="https://dl.acm.org/doi/10.1145/3744257.3744266"
          target="_blank"
          rel="noopener noreferrer"
        >
          W4A 2025 study
        </a>{" "}
        found ChatGPT and Claude &ldquo;primarily replicate existing design
        patterns,&rdquo; perpetuating hard-to-read text, poor contrast, and
        small touch targets. And a{" "}
        <a
          href="https://arxiv.org/abs/2503.15885"
          target="_blank"
          rel="noopener noreferrer"
        >
          2025 comparison study
        </a>{" "}
        found LLMs often beat human code on basic checks like contrast and alt
        text, yet consistently fail on ARIA: the invisible layer a screenshot
        can never show. Everything a quick glance validates, the model does
        fine. Everything it can&rsquo;t, the model fakes.
      </p>

      <PullStat num="84%">
        of websites generated by ChatGPT contained accessibility violations, in
        a study where 88 web developers wrote the prompts.{" "}
        <a
          href="https://dl.acm.org/doi/full/10.1145/3677846.3677854"
          target="_blank"
          rel="noopener noreferrer"
        >
          Aljedaani et al., W4A 2024
        </a>
      </PullStat>

      <p>
        The sharpest evidence is a real audit.{" "}
        <a
          href="https://axesslab.com/lovable/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Axess Lab tested a Lovable-built site
        </a>{" "}
        in May 2026. It scored 100% on Lovable&rsquo;s own automated
        accessibility check, which runs axe under the hood. Then a blind
        screen-reader user tried it.
      </p>
      <Roast>
        The dashboard said 100% accessible. The first blind user to touch it
        got trapped behind an open menu within minutes.
      </Roast>
      <Receipt rule="Axess Lab · Lovable audit, May 2026">
        Focus escaped behind open menus and modals. A live region kept
        interrupting the screen reader. Navigation never moved focus. The menu
        button never announced whether it was open. And a button whose visible
        text said &ldquo;Get tickets&rdquo; carried an aria-label saying
        &ldquo;Register for tickets,&rdquo; a WCAG 2.5.3 Label in Name failure.
        All of it invisible to the automated check that awarded 100%.
      </Receipt>
      <p>
        Hold onto that case. It anchors everything below: automated scores
        measure what a machine can see, and vibe-coded apps fail precisely in
        the places machines and screenshots don&rsquo;t look.
      </p>

      <h2>The 7 defects, and the 2-minute check for each</h2>

      <h3>1. Gray-on-white text that fails contrast</h3>
      <p>
        The AI ships tasteful, muted, illegible gray. It learned the look from
        the low-contrast pages WebAIM keeps flagging as the web&rsquo;s most
        common failure. The 2-minute check:
        squint at your app, or step 2 meters back. Anything that disappears is
        below the WCAG 1.4.3 threshold of 4.5:1 for normal text. For receipts,
        pull your actual text and button hex values into this:
      </p>
      <ContrastChecker />
      <p>
        The default above is the exact gray an AI generator loves. Fix:
        replace the muted-text token in your theme once, and every instance
        inherits it. ⚡ Quick win · ~1 hr.
      </p>

      <h3>2. Focus states that don&rsquo;t exist, modals you can&rsquo;t leave</h3>
      <p>
        Generated CSS routinely strips focus outlines because they look untidy
        in a screenshot, and generated modals rarely trap focus correctly, so
        Tab wanders behind the overlay, exactly what the Lovable audit found.
        The check: unplug your mouse and Tab through your money flow. If you
        ever can&rsquo;t see where you are, or can&rsquo;t get out of a dialog,
        that is the defect.
      </p>
      <Ticket
        id="VIBE-2"
        sev="Blocker"
        title="Checkout modal loses keyboard focus behind the overlay"
        fields={[
          {
            label: "Evidence",
            value:
              "Tabbing inside the modal reaches elements behind it; focus outline is removed globally, so keyboard users cannot tell where they are.",
          },
          {
            label: "Rule",
            value: "WCAG 2.4.11 · Focus not obscured (AA, new in 2.2)",
          },
          {
            label: "Fix",
            value:
              "Restore a visible :focus-visible outline, trap focus inside open dialogs, return it to the trigger on close.",
          },
          { label: "Effort", value: "⚡ Quick win · ~1 hr with a dialog library" },
        ]}
      />

      <h3>3. ARIA that lies</h3>
      <p>
        This is where LLMs fail hardest per the{" "}
        <a
          href="https://arxiv.org/abs/2503.15885"
          target="_blank"
          rel="noopener noreferrer"
        >
          2025 human-vs-LLM study
        </a>
        : attributes that look diligent and are wrong. Labels that don&rsquo;t
        match visible text, menu buttons that never announce open or closed,
        live regions that shout over the screen reader. Wrong ARIA is worse
        than no ARIA, because it confidently tells assistive tech a false
        story. The check: in devtools, compare each button&rsquo;s aria-label
        to what it visibly says; they must match.
      </p>
      <Ticket
        id="VIBE-3"
        sev="Major"
        title="Button text and aria-label disagree across primary actions"
        fields={[
          {
            label: "Evidence",
            value:
              "Visible text says one thing, aria-label another (the Lovable audit's \"Get tickets\" vs \"Register for tickets\"). Voice control users saying the visible label hit nothing.",
          },
          { label: "Rule", value: "WCAG 2.5.3 · Label in name (A)" },
          {
            label: "Fix",
            value:
              "Delete decorative aria-labels; where one is needed, start it with the visible text. Announce state on toggles with aria-expanded.",
          },
          { label: "Effort", value: "⚡ Quick win · ~1 hr" },
        ]}
      />

      <h3>4. Errors that fail silently</h3>
      <p>
        You prompted for the happy path, so that is what got built. When the
        API call fails, the generated catch block logs to a console no user
        will ever open, and the button just... finishes. The user thinks the
        form submitted. It did not. The check: open devtools, switch the
        network to offline, and click save. If the UI shrugs, so will your
        users, right before they churn.
      </p>
      <Ticket
        id="VIBE-4"
        sev="Blocker"
        title="Failed requests show no error state; users believe writes succeeded"
        fields={[
          {
            label: "Evidence",
            value:
              "Killing the network mid-save produces no message, no retry, no preserved input. The failure exists only in the console.",
          },
          {
            label: "Rule",
            value: "Nielsen #9 · Help users recognize, diagnose, recover from errors",
          },
          {
            label: "Fix",
            value:
              "Design one reusable error state: plain-language message, retry action, input preserved. Wire every mutation to it.",
          },
          { label: "Effort", value: "⚒ Deep fix · ~2 days" },
        ]}
      />

      <h3>5. Empty states and loading states nobody generated</h3>
      <p>
        The AI built your dashboard around demo data, so it has never been
        empty. A real new user gets a blank void with no hint of what to do
        first, and slow connections get layout jumps instead of loading
        feedback. The check: create a fresh account and throttle the network
        in devtools. Rules: Nielsen #6 (recognition rather than recall) for
        the empty state, Nielsen #1 (visibility of status) for the loading
        one. Fix: one empty state per core screen that names the first action,
        plus skeletons on anything async. ⚡ Quick win · ~1 hr per screen.
      </p>

      <h3>6. Touch targets under 24px</h3>
      <p>
        Dense little icon buttons look precise in a screenshot and miserable
        under a thumb.{" "}
        <a
          href="https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html"
          target="_blank"
          rel="noopener noreferrer"
        >
          WCAG 2.5.8 (AA, new in 2.2)
        </a>{" "}
        sets the floor at 24×24 CSS pixels or equivalent spacing. The check:
        on your phone, tap every icon in your main list view with your thumb,
        not your index finger. Every miss is a finding. Fix: pad the hit area,
        not the icon. ⚡ Quick win · ~1 hr.
      </p>

      <h3>7. Forms that re-ask what they already know</h3>
      <p>
        Each generated screen was born in a separate prompt, so nothing shares
        state: the checkout re-asks the email from signup, billing re-asks
        shipping.{" "}
        <a
          href="https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/"
          target="_blank"
          rel="noopener noreferrer"
        >
          WCAG 3.3.7 Redundant entry (Level A)
        </a>{" "}
        says don&rsquo;t ask for the same information twice in a session. The
        check: run signup through checkout and count every field you type
        twice. Fix: auto-populate or offer &ldquo;same as above.&rdquo; ⚡
        Quick win · ~1 hr.
      </p>

      <h2>The 20-minute pre-launch pass</h2>
      <p>
        Run this on the one flow that makes you money, in order. It combines
        all 7 checks and needs nothing you don&rsquo;t already have.
      </p>
      <ol>
        <li>
          <strong>Keyboard-only walk-through (6 min).</strong> Unplug the
          mouse. Signup to paid action using only Tab, Shift+Tab, Enter, and
          Escape. You must always see where focus is, and always be able to
          leave a modal.
        </li>
        <li>
          <strong>Contrast pass (3 min).</strong> Squint test on every screen,
          then run your body text, muted text, and primary button through the
          checker above. 4.5:1 for text, 3:1 for large text and UI components.
        </li>
        <li>
          <strong>Screen-reader smoke test (5 min).</strong> VoiceOver is
          Cmd+F5 on a Mac; NVDA is a free download on Windows. Tab through the
          money flow and listen: does every button announce what it visibly
          says, and does the menu say when it is open?
        </li>
        <li>
          <strong>Error-state hunt (4 min).</strong> Submit every form empty.
          Then go offline in devtools mid-save. Every silent failure is a
          Blocker.
        </li>
        <li>
          <strong>Fresh-eyes finish (2 min).</strong> New account, phone in
          hand: is the first screen self-explanatory, and can your thumb hit
          everything?
        </li>
      </ol>
      <p>
        Log each miss as a ticket with a severity, the rule it breaks, and an
        effort tag, same shape as the tickets above. The full method, extended
        beyond accessibility, is in{" "}
        <Link href="/blog/founder-ux-audit-checklist">
          the founder&rsquo;s UX audit checklist
        </Link>
        .
      </p>

      <h2>What this pass won&rsquo;t catch</h2>
      <p>
        Be honest about the limits. Automated checkers only see the
        machine-detectable subset of failures; WebAIM itself cautions that its
        95.9% understates the true rate, and the Lovable case shows a perfect
        automated score coexisting with a product a blind user could not
        operate. Your 20-minute pass beats any scanner because you actually
        use the product, but you are still one evaluator who wrote the
        prompts, testing your own baby. You can also ask the model to critique
        its own output:{" "}
        <a
          href="https://dl.acm.org/doi/full/10.1145/3677846.3677854"
          target="_blank"
          rel="noopener noreferrer"
        >
          ChatGPT fixed 73.4% of its own violations when asked
        </a>
        . The catch: the fix rate is worst exactly where the defects live,
        keyboard-level operable issues. (The how-to is in{" "}
        <Link href="/blog/chatgpt-ux-audit-prompts">
          ChatGPT UX audit prompts
        </Link>
        .)
      </p>
      <p>
        One legal footnote, minus the fear-mongering: the EU&rsquo;s{" "}
        <a
          href="https://accessible-eu-centre.ec.europa.eu/content-corner/news/eaa-comes-effect-june-2025-are-you-ready-2025-01-31_en"
          target="_blank"
          rel="noopener noreferrer"
        >
          European Accessibility Act has been enforceable since 28 June 2025
        </a>{" "}
        for products and services newly sold to EU consumers (baseline
        incorporates WCAG 2.1 AA), and the US ADA Title II rule holds state
        and local government sites to WCAG 2.1 AA on{" "}
        <a
          href="https://www.federalregister.gov/documents/2026/04/20/2026-07663/extension-of-compliance-dates-for-nondiscrimination-on-the-basis-of-disability-accessibility-of-web"
          target="_blank"
          rel="noopener noreferrer"
        >
          deadlines now set for 2027 and 2028
        </a>
        . If you sell into the EU, the checklist above stopped being optional
        last year.
      </p>
      <p>
        This defect set is also precisely what an agent-based audit catches,
        because the agent does what the scanner can&rsquo;t: it signs up, tabs
        through your modals, kills its own happy path, and files each finding
        as a ticket citing the rule it breaks, WCAG 2.2 or Nielsen by name.
        That is what <Link href="/">ClapBack</Link> does with a URL and no SDK,
        and{" "}
        <Link href="/blog/what-is-an-ai-ux-audit">
          what an AI UX audit involves
        </Link>{" "}
        explains where an agent fits next to a human screen-reader tester
        (short answer: it replaces the scanner, not the human).
      </p>

      <Sources
        items={[
          {
            label:
              "TechCrunch · A quarter of YC W25 codebases almost entirely AI-generated (Mar 2025)",
            href: "https://techcrunch.com/2025/03/06/a-quarter-of-startups-in-ycs-current-cohort-have-codebases-that-are-almost-entirely-ai-generated/",
          },
          {
            label:
              "Aljedaani et al. · Does ChatGPT Generate Accessible Code? (W4A 2024)",
            href: "https://dl.acm.org/doi/full/10.1145/3677846.3677854",
          },
          {
            label:
              "Suh et al. · Human or LLM? Accessible Code Generation Capability (arXiv 2503.15885)",
            href: "https://arxiv.org/abs/2503.15885",
          },
          {
            label:
              "W4A 2025 · When LLM-Generated Code Perpetuates UI Accessibility Barriers",
            href: "https://dl.acm.org/doi/10.1145/3744257.3744266",
          },
          {
            label:
              "Axess Lab · Lovable's AI built a 100% accessible site, or did it? (May 2026)",
            href: "https://axesslab.com/lovable/",
          },
          {
            label: "WebAIM · The WebAIM Million, 2026 edition",
            href: "https://webaim.org/projects/million/",
          },
          {
            label: "W3C WAI · What's new in WCAG 2.2",
            href: "https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/",
          },
          {
            label: "W3C · Understanding target size (minimum), SC 2.5.8",
            href: "https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html",
          },
          {
            label: "AccessibleEU · The EAA comes into effect June 2025",
            href: "https://accessible-eu-centre.ec.europa.eu/content-corner/news/eaa-comes-effect-june-2025-are-you-ready-2025-01-31_en",
          },
          {
            label:
              "Federal Register · Extension of ADA Title II web compliance dates (Apr 2026)",
            href: "https://www.federalregister.gov/documents/2026/04/20/2026-07663/extension-of-compliance-dates-for-nondiscrimination-on-the-basis-of-disability-accessibility-of-web",
          },
          {
            label: "NN/g · 10 usability heuristics (Nielsen, 1994)",
            href: "https://www.nngroup.com/articles/ten-usability-heuristics/",
          },
        ]}
      />
    </>
  );
}
